name: forum
services:
  MySQL-forum:
    image: mysql:latest
    container_name: mysql_forum
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "forum"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "mdp"
    volumes:
      - ./data/mysql:/var/lib/mysql
  adminer-forum:
    image: adminer
    container_name: adminer-forum
    ports:
      - "8080:8080"